### PR TITLE
Adding Pittsburgh to #CoffeeOps

### PR DESCRIPTION
**Pull request by cwest**

### CODE REVIEW

**Comment by colindean** [comment]
Cahnt me in fer coffee 'n'at.

**Comment by MandaBrown** [comment]
:+1: :goat:

**Comment by meatballhat** [comment]
UM YES WANT

**Comment by emdantrim** [comment]
hellote.

**Comment by iennae** [comment]
Sounds Awesome !

**Comment by normanjoyner** [comment]
:+1:

**Pull request merged**
